import '@/app/globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Roboto } from "next/font/google";
import { Toaster } from 'sonner';

const roboto = Roboto({ subsets: ["latin"], weight: '400' });


export const metadata = {
  title: 'Pagination',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${roboto.className} text-[rgb(93,90,90)] bg-[whitesmoke] dark:bg-[rgb(93,90,90)] dark:text-[whitesmoke] `}>
        <Navbar />

        <main className='w-full my-20 p-5 md:mx-auto'>
          {children}
        </main>

        <Footer />
        <Toaster position='top-right' richColors />
      </body>
    </html>
  )
}
